plugins: inline convert web lastgenre bpd embedart duplicates missing play replaygain

play:
  command: mpv --vid=no --shuffle $args

lastgenre:
  source: track

replaygain:
  backend: gstreamer
  targetlevel: 70
